/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.cslJDBC;
import Capa_Negocio.Tipo_Usuario;
import Capa_Negocio.clsUsuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author holce
 */
public class Registrar_Usuario extends javax.swing.JDialog {

    clsUsuario objUsuario = new clsUsuario();                
;
    
    public Registrar_Usuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        btnRegistrar.setEnabled(false);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lbllogogrande = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        lblConfirmarContraseña = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        validarusuario = new javax.swing.JLabel();
        validarconfirmarcontraseña = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        PasswordConfirm = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        validarCorreo = new javax.swing.JLabel();
        ValidarTelefono = new javax.swing.JLabel();
        ValidarApellido = new javax.swing.JLabel();
        validarNobmre = new javax.swing.JLabel();
        validarcontraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Docente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Login_pequeño.png"))); // NOI18N

        lbllogogrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Login_Grande.png"))); // NOI18N

        lblnombres.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblnombres.setText("Nombres:");

        lblapellidos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblapellidos.setText("Apellidos:");

        lblusuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblusuario.setText("Usuario:");

        lblcontraseña.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblcontraseña.setText("Contraseña:");

        lblConfirmarContraseña.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblConfirmarContraseña.setText("Confirmar Contraseña:");

        lblCorreo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCorreo.setText("Correo de Trabajo:");

        lblTelefono.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        validarusuario.setText("*");

        validarconfirmarcontraseña.setText("*");

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });

        PasswordConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordConfirmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordConfirmKeyTyped(evt);
            }
        });

        jLabel1.setText("Tipo:");

        validarCorreo.setText("*");

        ValidarTelefono.setText("*");

        ValidarApellido.setText("*");

        validarNobmre.setText("*");

        validarcontraseña.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbllogo)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblapellidos)
                                        .addComponent(lblusuario)
                                        .addComponent(lblCorreo)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblConfirmarContraseña)
                                            .addComponent(lblcontraseña, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(lblnombres)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lblTelefono)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PasswordConfirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                                .addGap(47, 47, 47)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(validarconfirmarcontraseña)
                                                    .addComponent(validarusuario)
                                                    .addComponent(validarCorreo)
                                                    .addComponent(ValidarTelefono)
                                                    .addComponent(validarcontraseña))))
                                        .addGap(0, 5, Short.MAX_VALUE))
                                    .addComponent(txtNombres))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValidarApellido)
                            .addComponent(validarNobmre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lbllogogrande)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblnombres)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblapellidos)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValidarApellido)))
                            .addComponent(validarNobmre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblusuario)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validarusuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcontraseña)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validarcontraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmarContraseña)
                            .addComponent(validarconfirmarcontraseña)
                            .addComponent(PasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validarCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidarTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbllogogrande, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void validar(){
    
        if(txtNombres.getText().isEmpty()){
            validarNobmre.setText("X");
            validarNobmre.setForeground(Color.red);
        }else{
            validarNobmre.setText("Ok");
            validarNobmre.setForeground(Color.green);
        }
        
        if(txtApellidos.getText().isEmpty()){
            ValidarApellido.setText("X");
            ValidarApellido.setForeground(Color.red);
        }else{
            ValidarApellido.setText("Ok");
            ValidarApellido.setForeground(Color.green);
        }
        
        if(txtusuario.getText().isEmpty()){
            validarusuario.setText("X");
            validarusuario.setForeground(Color.red);
        }       
        else{
            validarusuario.setText("Ok");
            validarusuario.setForeground(Color.green);
        }
        
       if(Password.getText().isEmpty()){
            validarcontraseña.setText("X");
            validarcontraseña.setForeground(Color.red);
        }else{
            validarcontraseña.setText("Ok");
            validarcontraseña.setForeground(Color.green);
        }
       
        if(PasswordConfirm.getText().isEmpty()){
            validarconfirmarcontraseña.setText("X");
            validarconfirmarcontraseña.setForeground(Color.red);
        }else if(Password.getText().equals(PasswordConfirm.getText())){
            validarconfirmarcontraseña.setText("Ok");
            validarconfirmarcontraseña.setForeground(Color.green);            
        }else{
            validarconfirmarcontraseña.setText("Incompatible Password");
            validarconfirmarcontraseña.setForeground(Color.red);
        }        
        if(txtcorreo.getText().isEmpty()){
            validarCorreo.setText("X");
            validarCorreo.setForeground(Color.red);
        }else if (!txtcorreo.getText().contains("@") || !txtcorreo.getText().contains(".")){
            validarCorreo.setText("Correo Inválido");
            validarCorreo.setForeground(Color.red);
        }else{
            validarCorreo.setText("Ok");
            validarCorreo.setForeground(Color.green);
        }
        
        if(txttelefono.getText().isEmpty()){
            ValidarTelefono.setText("X");
            ValidarTelefono.setForeground(Color.red);
        }else{
            ValidarTelefono.setText("Ok");
            ValidarTelefono.setForeground(Color.green);
        } 
        
        if(txtNombres.getText().isEmpty()|| txtApellidos.getText().isEmpty() || txtcorreo.getText().isEmpty() || 
                txttelefono.getText().isEmpty()|| txtusuario.getText().isEmpty()|| Password.getText().isEmpty() || 
                PasswordConfirm.getText().isEmpty()){
                btnRegistrar.setEnabled(false);      
        }else{
                btnRegistrar.setEnabled(true);
        }
    }
    
    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
                if(txtusuario.getText().equals(clsUsuario.compararUsuario(txtusuario.getText()))){
                    objUsuario.setNombre(txtNombres.getText());
                    objUsuario.setApellido(txtApellidos.getText());
                    objUsuario.setTipo((Tipo_Usuario) cmbTipoUsuario.getSelectedItem());
                    objUsuario.setNickname(txtusuario.getText());
                    objUsuario.setContraseña(Password.getText());
                    objUsuario.setCorreo(txtcorreo.getText());
                    objUsuario.setTelefono(txttelefono.getText());
                    objUsuario.registrar();                                     
                }else{
                    JOptionPane.showMessageDialog(null, "Nick de Usuario ya en Uso");
                }
        } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al registrar Usuario");
        }
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        listarCombo();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        if(txtNombres.getText().length()== 50){
           evt.consume();
       }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        if(txtApellidos.getText().length()== 60){
           evt.consume();
       }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        if(txtusuario.getText().length()== 25){
           evt.consume();
       }
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        if(Password.getText().length()== 10){
           evt.consume();
       }
    }//GEN-LAST:event_PasswordKeyTyped

    private void PasswordConfirmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordConfirmKeyTyped
        if(PasswordConfirm.getText().length()== 10){
           evt.consume();
       }
    }//GEN-LAST:event_PasswordConfirmKeyTyped

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        if(txtcorreo.getText().length()== 80){
           evt.consume();
       }
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        char caracter = evt.getKeyChar();
        if(txttelefono.getText().length()== 11){
            evt.consume();
        }       
        if((caracter < '0') || (caracter > '9') && (caracter != '\b')){
            evt.consume();
        }
               
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        validar();
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyReleased
        validar();
    }//GEN-LAST:event_txtApellidosKeyReleased

    private void txtusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyReleased
        validar();
    }//GEN-LAST:event_txtusuarioKeyReleased

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        validar();
    }//GEN-LAST:event_PasswordKeyReleased

    private void PasswordConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordConfirmKeyReleased
        validar();
    }//GEN-LAST:event_PasswordConfirmKeyReleased

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        validar();
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txttelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyReleased
        validar();
    }//GEN-LAST:event_txttelefonoKeyReleased

    /**
     * @param args the command line arguments
     */
   
    private void listarCombo(){
        try {
            for(Tipo_Usuario combo:Tipo_Usuario.listar()){
                cmbTipoUsuario.addItem(combo.getDescripcion());
            }
        } catch (Exception e) {
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField PasswordConfirm;
    private javax.swing.JLabel ValidarApellido;
    private javax.swing.JLabel ValidarTelefono;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmarContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogogrande;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel validarCorreo;
    private javax.swing.JLabel validarNobmre;
    private javax.swing.JLabel validarconfirmarcontraseña;
    private javax.swing.JLabel validarcontraseña;
    private javax.swing.JLabel validarusuario;
    // End of variables declaration//GEN-END:variables
}
